# Generated by Django 5.2 on 2025-04-23 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('cover_img', models.ImageField(help_text='Если его нет, то берется родительское изображение', upload_to='', verbose_name='Изображение раздела')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.page')),
            ],
        ),
    ]
