# Generated by Django 5.2 on 2025-04-25 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_page_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.TextField(blank=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='articles.page'),
        ),
    ]
