# Generated by Django 5.2 on 2025-04-26 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_page_name_alter_page_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cover_img',
            field=models.ImageField(blank=True, help_text='Если его нет, то берется родительское изображение', null=True, upload_to='', verbose_name='Изображение раздела'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('MAIN', 'Главная страница'), ('CATEGORY', 'Страница раздела'), ('PAGE', 'Страница'), ('GALLERY', 'Страница галереи'), ('BOOK', 'Страница книги')], default='PAGE', verbose_name='Тип страницы'),
        ),
        migrations.CreateModel(
            name='PageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='articles.page')),
            ],
        ),
    ]
