# Generated by Django 5.2 on 2025-04-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_page_cover_img_alter_page_type_pagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержимое'),
        ),
    ]
