# Generated by Django 5.2 on 2025-04-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='depth',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Глубина страницы'),
        ),
    ]
