# Generated by Django 5.2 on 2025-05-02 00:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_page_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('PAGE', 'Страница'), ('GALLERY', 'Страница галереи'), ('BOOK', 'Страница книги')], default='PAGE', verbose_name='Тип страницы'),
        ),
    ]
