# Generated by Django 5.2 on 2025-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_page_content_alter_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='original_url',
            field=models.TextField(default='', verbose_name='Ссылка на оригинальную страницу'),
        ),
        migrations.AlterField(
            model_name='page',
            name='depth',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Необходим для построения области навигации', verbose_name='Глубина страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('PAGE', 'Страница'), ('GALLERY_CATEGORY', 'Папка галерей'), ('GALLERY', 'Страница галереи'), ('BOOK', 'Страница книги')], default='PAGE', verbose_name='Тип страницы'),
        ),
    ]
