# Generated by Django 5.2 on 2025-05-16 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_page_original_url_alter_page_depth_alter_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('PAGE', 'Страница'), ('GALLERY_CATEGORY', 'Папка галерей'), ('GALLERY', 'Страница галереи'), ('VIDEO_CATEGORY', 'Папка видеоматериалов'), ('VIDEO', 'Страница видеоматериала'), ('BOOK', 'Страница книги')], default='PAGE', verbose_name='Тип страницы'),
        ),
    ]
