# Generated by Django 5.2 on 2025-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_page_options_remove_page_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('PAGE', 'Страница'), ('CATEGORY', 'Категория'), ('GALLERY_CATEGORY', 'Папка галерей'), ('GALLERY', 'Страница галереи'), ('VIDEO_CATEGORY', 'Папка видеоматериалов'), ('VIDEO', 'Страница видеоматериала'), ('BOOK_CATEGORY', 'Папка книг'), ('BOOK', 'Страница книги')], default='PAGE', verbose_name='Тип страницы'),
        ),
    ]
