# Generated by Django 5.2 on 2025-05-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_page_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='page',
            name='depth',
        ),
    ]
