# Generated by Django 5.2 on 2025-06-04 01:23

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_page_cover_img_remove_page_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagefile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=articles.models.custom_upload_to, verbose_name='Файл'),
        ),
    ]
