# Generated by Django 5.2 on 2025-06-05 02:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержимое'),
        ),
    ]
