# Generated by Django 5.2 on 2025-06-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('PAGE', 'Страница'), ('SECTION', 'Раздел'), ('CATEGORY', 'Категория'), ('AUDIO_CATEGORY', 'Папка аудиоматериалов'), ('AUDIO', 'Аудиоматериал'), ('GALLERY_CATEGORY', 'Папка галерей'), ('GALLERY', 'Страница галереи'), ('VIDEO_CATEGORY', 'Папка видеоматериалов'), ('VIDEO', 'Страница видеоматериала'), ('BOOK_CATEGORY', 'Папка книг'), ('BOOK', 'Страница книги')], default='PAGE', verbose_name='Тип страницы'),
        ),
    ]
